spring.application.name=login
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/react-apps
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/react-apps/protocol/openid-connect/certs
server.port=9090

# Set logging level for request logging filter
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

#spring.main.allow-bean-definition-overriding=true
